const $=s=>document.querySelector(s),canvas=$('#previewCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),empty=$('#emptyState'),download=$('#downloadBtn'),badge=$('#modeBadge'),size=$('#sizeBadge'),count=$('#modeCount');
const controls={resolution:$('#resolutionRange'),threshold:$('#thresholdRange'),contrast:$('#contrastRange'),density:$('#densityRange'),strength:$('#strengthRange'),motion:$('#motionRange'),artContrast:$('#artContrastRange')},outputs=Object.fromEntries(Object.keys(controls).map(k=>[k,$(`#${k}Value`)])),modes=[...document.querySelectorAll('.mode-chip')],names=Object.fromEntries(modes.map(b=>[b.dataset.mode,b.textContent.toUpperCase()]));
const state={image:null,url:null,mode:'floyd',inverted:false,timer:null,language:localStorage.getItem('dp-language')||'fr'},b4=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]],kernels={floyd:[[1,0,7/16],[-1,1,3/16],[0,1,5/16],[1,1,1/16]],atkinson:[[1,0,1/8],[2,0,1/8],[-1,1,1/8],[0,1,1/8],[1,1,1/8],[0,2,1/8]]};
const clamp=(v,a=0,b=255)=>Math.max(a,Math.min(b,v)),lum=(r,g,b)=>.2126*r+.7152*g+.0722*b,hash=(x,y)=>{let n=(x*374761393+y*668265263)^(x*y*1274126177);n=(n^(n>>>13))*1274126177;return((n^(n>>>16))>>>0)/4294967295};
function adjusted(r,g,b,c=+controls.contrast.value){const f=259*(c+255)/(255*(259-c));return clamp(f*(lum(r,g,b)-128)+128)}
function target(img){const w=+controls.resolution.value,iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height;return{width:w,height:Math.max(1,Math.round(w*ih/iw))}}
function forceBW(d){for(let i=0;i<d.length;i+=4){const v=d[i]<128?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}}
function invert(d){for(let i=0;i<d.length;i+=4)d[i]=d[i+1]=d[i+2]=d[i]===0?255:0}
function diffusion(im,type){const{data,width:w,height:h}=im,a=new Float32Array(w*h),t=+controls.threshold.value;for(let i=0,p=0;i<data.length;i+=4,p++)a[p]=adjusted(data[i],data[i+1],data[i+2]);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,n=a[i]<t?0:255,e=a[i]-n;a[i]=n;kernels[type].forEach(([dx,dy,k])=>{const nx=x+dx,ny=y+dy;if(nx>=0&&nx<w&&ny<h)a[ny*w+nx]+=e*k})}for(let p=0,i=0;p<a.length;p++,i+=4)data[i]=data[i+1]=data[i+2]=a[p]<128?0:255}
function ordered(im){const{data,width:w}=im,t0=+controls.threshold.value;for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%w,y=(p/w)|0,t=t0+(((b4[y%4][x%4]+.5)/16)-.5)*180,v=adjusted(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v}}
function gray(im){const a=new Float32Array(im.width*im.height),c=+controls.artContrast.value;for(let p=0,i=0;p<a.length;p++,i+=4)a[p]=adjusted(im.data[i],im.data[i+1],im.data[i+2],c)/255;return a}
const sample=(a,w,h,x,y)=>a[clamp(Math.round(y),0,h-1)*w+clamp(Math.round(x),0,w-1)];
function paper(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;const o=c.getContext('2d',{willReadFrequently:true});o.fillStyle='#fff';o.fillRect(0,0,w,h);o.fillStyle=o.strokeStyle='#000';o.lineCap=o.lineJoin='round';return{c,o}}
function finish(c){const im=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height);forceBW(im.data);return im}
function halftone(im){const w=im.width,h=im.height,g=gray(im),{c,o}=paper(w,h),d=+controls.density.value/100,s=+controls.strength.value/100,m=+controls.motion.value/100,sp=18-d*13.5,step=Math.max(2,sp*.42),max=sp*(.38+s*.58);for(let row=0,y=sp/2;y<h+sp;y+=sp,row++){const top=[],bot=[];for(let x=-step;x<=w+step;x+=step){const yy=y+(Math.sin(x*.022+row*.73)+Math.sin(x*.008-row*.41)*.55)*sp*.38*m,dark=Math.pow(clamp(1-sample(g,w,h,x,yy),0,1),.72),th=Math.max(0,dark*max-.22);top.push([x,yy-th/2]);bot.push([x,yy+th/2])}o.beginPath();o.moveTo(...top[0]);top.slice(1).forEach(p=>o.lineTo(...p));bot.reverse().forEach(p=>o.lineTo(...p));o.closePath();o.fill()}return finish(c)}
function banknote(im){const w=im.width,h=im.height,g=gray(im),{c,o}=paper(w,h),d=+controls.density.value/100,s=+controls.strength.value/100,m=+controls.motion.value/100,sp=15-d*10;o.lineWidth=.7+s*2;for(let row=0,y=sp/2;y<h;y+=sp,row++){o.beginPath();let on=false;for(let x=0;x<=w;x+=2){const dark=1-sample(g,w,h,x,y),yy=y+Math.sin(x*.025+row*.7)*sp*.35*m+(dark-.5)*sp*m;if(dark>.12){on?o.lineTo(x,yy):o.moveTo(x,yy);on=true}else on=false}o.stroke()}return finish(c)}
function woodcut(im){const w=im.width,h=im.height,g=gray(im),{c,o}=paper(w,h),d=+controls.density.value/100,s=+controls.strength.value/100,m=+controls.motion.value/100,cell=14-d*8;o.lineWidth=.8+s*2.2;for(let y=0;y<h;y+=cell)for(let x=0;x<w;x+=cell){const dark=1-sample(g,w,h,x+cell/2,y+cell/2);if(dark<.18)continue;for(let k=0;k<1+dark*3;k++){const a=-.8+(hash(x+k,y)-.5)*.9*m,len=cell*(.7+dark*1.2),cx=x+cell/2+(hash(x,y+k)-.5)*cell*.35,cy=y+cell/2+(k-dark*1.5)*1.8;o.beginPath();o.moveTo(cx-Math.cos(a)*len/2,cy-Math.sin(a)*len/2);o.lineTo(cx+Math.cos(a)*len/2,cy+Math.sin(a)*len/2);o.stroke()}}return finish(c)}
function stipple(im){const w=im.width,h=im.height,g=gray(im),{c,o}=paper(w,h),d=+controls.density.value/100,s=+controls.strength.value/100,cell=12-d*8;for(let y=cell/2;y<h;y+=cell)for(let x=cell/2;x<w;x+=cell){const dark=1-sample(g,w,h,x,y);if(hash(x,y)>Math.pow(dark,.75))continue;const r=.45+dark*(.7+s*2.4),jx=(hash(x+3,y)-.5)*cell*.7,jy=(hash(x,y+7)-.5)*cell*.7;o.beginPath();o.arc(x+jx,y+jy,r,0,Math.PI*2);o.fill()}return finish(c)}
function fingerprint(im){const w=im.width,h=im.height,g=gray(im),{c,o}=paper(w,h),d=+controls.density.value/100,s=+controls.strength.value/100,m=+controls.motion.value/100,cx=w/2,cy=h/2,max=Math.hypot(w,h)*.58,gap=13-d*8;o.lineWidth=.7+s*1.8;for(let r=gap;r<max;r+=gap){o.beginPath();let on=false;for(let a=0;a<=Math.PI*2+.05;a+=.035){const x0=cx+Math.cos(a)*r,y0=cy+Math.sin(a)*r,dark=1-sample(g,w,h,x0,y0),rr=r+(dark-.5)*gap*1.8*m,x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;if(dark>.1){on?o.lineTo(x,y):o.moveTo(x,y);on=true}else on=false}o.stroke()}return finish(c)}
function topographic(im){const w=im.width,h=im.height,g=gray(im),{c,o}=paper(w,h),d=+controls.density.value/100,s=+controls.strength.value/100,levels=Math.round(4+d*10),step=2,px=Math.max(1,.7+s*1.6);for(let y=step;y<h-step;y+=step)for(let x=step;x<w-step;x+=step){const q=Math.floor(sample(g,w,h,x,y)*levels);if(Math.floor(sample(g,w,h,x+step,y)*levels)!==q||Math.floor(sample(g,w,h,x,y+step)*levels)!==q)o.fillRect(x,y,px,px)}return finish(c)}
const art=new Set(['halftone','banknote','woodcut','stipple','fingerprint','topographic']),renderers={halftone,banknote,woodcut,stipple,fingerprint,topographic};
function render(){if(!state.image)return;try{const{width,height}=target(state.image);canvas.width=width;canvas.height=height;ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(state.image,0,0,width,height);let im=ctx.getImageData(0,0,width,height);if(state.mode==='floyd'||state.mode==='atkinson')diffusion(im,state.mode);else if(state.mode==='bayer')ordered(im);else im=renderers[state.mode](im);forceBW(im.data);if(state.inverted)invert(im.data);ctx.putImageData(im,0,0);empty.hidden=true;size.textContent=`${width} × ${height}`;download.disabled=false}catch(e){console.error(e);empty.hidden=false;empty.querySelector('strong').textContent='Erreur de rendu';empty.querySelector('span').textContent=e.message}}
function labels(){Object.entries(controls).forEach(([k,c])=>{if(c&&outputs[k])outputs[k].textContent=(k==='contrast'||k==='artContrast')&&+c.value>0?`+${c.value}`:c.value});badge.textContent=names[state.mode];count.textContent=`${modes.findIndex(b=>b.dataset.mode===state.mode)+1} / ${modes.length}`}
function groups(){const a=art.has(state.mode);$('#basicControls').hidden=a;$('#artControls').hidden=!a}
const presets={halftone:[68,88,18,48,'Densité','Épaisseur','Courbure'],banknote:[62,42,65,45,'Lignes','Trait','Relief'],woodcut:[58,68,72,52,'Densité','Trait','Irrégularité'],stipple:[72,58,20,42,'Points','Taille','Dispersion'],fingerprint:[66,48,72,46,'Anneaux','Trait','Déformation'],topographic:[68,48,10,55,'Niveaux','Trait','Relief']};
function preset(mode){const p=presets[mode];if(!p)return;[controls.density.value,controls.strength.value,controls.motion.value,controls.artContrast.value]=p;$('#densityLabel').textContent=p[4];$('#strengthLabel').textContent=p[5];$('#motionLabel').textContent=p[6]}
['cameraInput','libraryInput'].forEach(id=>$(`#${id}`).addEventListener('change',async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(state.url)URL.revokeObjectURL(state.url);state.url=URL.createObjectURL(file);const img=new Image();img.src=state.url;await img.decode();state.image=img;render()}));
modes.forEach(b=>b.addEventListener('click',()=>{clearTimeout(state.timer);state.mode=b.dataset.mode;modes.forEach(x=>x.classList.toggle('active',x===b));preset(state.mode);groups();labels();render()}));
Object.values(controls).forEach(c=>c?.addEventListener('input',()=>{labels();clearTimeout(state.timer);state.timer=setTimeout(render,45)}));
$('#invertBtn').addEventListener('click',()=>{state.inverted=!state.inverted;render()});$('#resetBtn').addEventListener('click',()=>location.reload());download.addEventListener('click',()=>canvas.toBlob(blob=>{const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=`dither-printer-${state.mode}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)},'image/png'));
const dialog=$('#settingsDialog');$('#settingsBtn').addEventListener('click',()=>dialog.showModal());$('#closeSettingsBtn').addEventListener('click',()=>dialog.close());$('#languageSelect').value=state.language;
function sync(){const p=localStorage.getItem('dp-show-printer')!=='false',t=localStorage.getItem('dp-show-test')!=='false';$('#showPrinterToggle').checked=p;$('#showTestToggle').checked=t;$('#printerPanel').hidden=!p;$('#testPrinterBtn').hidden=!t}
$('#showPrinterToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-printer',e.target.checked);sync()});$('#showTestToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-test',e.target.checked);sync()});$('#languageSelect').addEventListener('change',e=>localStorage.setItem('dp-language',e.target.value));sync();labels();groups();
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const rs=await navigator.serviceWorker.getRegistrations();await Promise.all(rs.map(r=>r.unregister()));if('caches'in window)await Promise.all((await caches.keys()).map(k=>caches.delete(k)))});