const canvas=document.querySelector('#previewCanvas');
const ctx=canvas.getContext('2d',{willReadFrequently:true});
const emptyState=document.querySelector('#emptyState');
const downloadBtn=document.querySelector('#downloadBtn');
const modeBadge=document.querySelector('#modeBadge');
const sizeBadge=document.querySelector('#sizeBadge');
const modeCount=document.querySelector('#modeCount');
const basicControls=document.querySelector('#basicControls');
const signalControls=document.querySelector('#signalControls');
const ids=['threshold','contrast','resolution','amount','density','flow','warp','turb','bias','signalContrast','brightness'];
const controls=Object.fromEntries(ids.map(id=>[id,document.querySelector(`#${id}Range`)]));
const outputs=Object.fromEntries(ids.map(id=>[id,document.querySelector(`#${id}Value`)]));
const state={image:null,mode:'threshold',inverted:false,renderTimer:null,language:localStorage.getItem('dp-language')||'fr'};
const modeNames={threshold:'SEUIL',floyd:'FLOYD–STEINBERG',atkinson:'ATKINSON',stucki:'STUCKI',sierra:'SIERRA LITE',bayer:'BAYER 4×4',ordered8:'ORDERED 8×8',bluenoise:'BLUE NOISE',riemersma:'RIEMERSMA',grain:'GRAIN',fieldRibbon:'FIELD RIBBON',fieldContour:'FIELD CONTOUR',fieldTopo:'FIELD TOPO',fieldWave:'FIELD WAVE',fieldRelief:'FIELD RELIEF',ascii:'ASCII'};
const fieldPresets={
 fieldRibbon:{amount:92,density:3.2,flow:70,warp:54,turb:4,bias:0,signalContrast:36,brightness:-4},
 fieldContour:{amount:74,density:4.4,flow:58,warp:62,turb:8,bias:0,signalContrast:40,brightness:-8},
 fieldTopo:{amount:52,density:5.6,flow:45,warp:38,turb:0,bias:0,signalContrast:48,brightness:-10},
 fieldWave:{amount:108,density:2.8,flow:82,warp:46,turb:18,bias:0,signalContrast:34,brightness:-6},
 fieldRelief:{amount:126,density:2.4,flow:66,warp:72,turb:6,bias:0,signalContrast:44,brightness:-12},
 ascii:{amount:82,density:4.2,flow:50,warp:35,turb:0,bias:0,signalContrast:40,brightness:0}
};
const i18n={fr:{tagline:'LABORATOIRE D’IMAGE THERMIQUE',camera:'Prise de vue',cameraHelp:'Ouvrir l’appareil photo',library:'Bibliothèque',libraryHelp:'Choisir une photo',addImage:'Ajoute une image',emptyHelp:'Elle sera convertie en noir et blanc pur.',renderStyle:'Rendu',threshold:'Seuil',grain:'Grain',contrast:'Contraste',resolution:'Résolution',brightness:'Luminosité',ipAddress:'Adresse IP',printerHelp:'L’iPhone et l’imprimante doivent être sur le même réseau.',printImage:'Imprimer l’image',invert:'Inverser',exportPng:'Exporter PNG',footer:'100 % noir · 100 % blanc · aucun gris',settings:'Paramètres',language:'Langue',showPrinting:'Afficher toute la partie impression',showTest:'Afficher le bouton de test',description:'Transformez vos photos en noir et blanc pur avec des tramages classiques, cinq rendus Field expérimentaux et un mode ASCII.'},en:{tagline:'THERMAL IMAGE LAB',camera:'Camera',cameraHelp:'Open the camera',library:'Library',libraryHelp:'Choose a photo',addImage:'Add an image',emptyHelp:'It will be converted to pure black and white.',renderStyle:'Rendering',threshold:'Threshold',grain:'Grain',contrast:'Contrast',resolution:'Resolution',brightness:'Brightness',ipAddress:'IP address',printerHelp:'The iPhone and printer must be on the same network.',printImage:'Print image',invert:'Invert',exportPng:'Export PNG',footer:'100% black · 100% white · no gray',settings:'Settings',language:'Language',showPrinting:'Show the entire printing section',showTest:'Show the printer test button',description:'Convert photos to pure black and white with classic dithering, five experimental Field renderers and an ASCII mode.'},es:{tagline:'LABORATORIO DE IMAGEN TÉRMICA',camera:'Cámara',cameraHelp:'Abrir la cámara',library:'Biblioteca',libraryHelp:'Elegir una foto',addImage:'Añade una imagen',emptyHelp:'Se convertirá a blanco y negro puro.',renderStyle:'Renderizado',threshold:'Umbral',grain:'Grano',contrast:'Contraste',resolution:'Resolución',brightness:'Brillo',ipAddress:'Dirección IP',printerHelp:'El iPhone y la impresora deben estar en la misma red.',printImage:'Imprimir imagen',invert:'Invertir',exportPng:'Exportar PNG',footer:'100 % negro · 100 % blanco · sin gris',settings:'Ajustes',language:'Idioma',showPrinting:'Mostrar toda la sección de impresión',showTest:'Mostrar el botón de prueba',description:'Convierte fotos a blanco y negro puro con tramado clásico, cinco renderizados Field experimentales y un modo ASCII.'}};
const bayer4=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]];
const bayer8=[[0,48,12,60,3,51,15,63],[32,16,44,28,35,19,47,31],[8,56,4,52,11,59,7,55],[40,24,36,20,43,27,39,23],[2,50,14,62,1,49,13,61],[34,18,46,30,33,17,45,29],[10,58,6,54,9,57,5,53],[42,26,38,22,41,25,37,21]];
const kernels={floyd:[[1,0,7/16],[-1,1,3/16],[0,1,5/16],[1,1,1/16]],atkinson:[[1,0,1/8],[2,0,1/8],[-1,1,1/8],[0,1,1/8],[1,1,1/8],[0,2,1/8]],stucki:[[1,0,8/42],[2,0,4/42],[-2,1,2/42],[-1,1,4/42],[0,1,8/42],[1,1,4/42],[2,1,2/42],[-2,2,1/42],[-1,2,2/42],[0,2,4/42],[1,2,2/42],[2,2,1/42]],sierra:[[1,0,.5],[-1,1,.25],[0,1,.25]]};
function clamp(v,min=0,max=255){return Math.max(min,Math.min(max,v));}
function luminance(r,g,b){return .2126*r+.7152*g+.0722*b;}
function adjustedGray(r,g,b,contrast=Number(controls.contrast.value),brightness=0){const f=(259*(contrast+255))/(255*(259-contrast));return clamp(f*(luminance(r,g,b)-128)+128+brightness);}
function getTargetSize(image){const width=Number(controls.resolution.value);return{width,height:Math.max(1,Math.round(width*image.naturalHeight/image.naturalWidth))};}
function forceBW(data){for(let i=0;i<data.length;i+=4){const v=data[i]<128?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function invertPixels(data){for(let i=0;i<data.length;i+=4)data[i]=data[i+1]=data[i+2]=data[i]===0?255:0;}
function applyThreshold(data){const t=+controls.threshold.value;for(let i=0;i<data.length;i+=4){const v=adjustedGray(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function applyDiffusion(imageData,type){const{data,width,height}=imageData,gray=new Float32Array(width*height),t=+controls.threshold.value;for(let i=0,p=0;i<data.length;i+=4,p++)gray[p]=adjustedGray(data[i],data[i+1],data[i+2]);for(let y=0;y<height;y++){const reverse=type==='riemersma'&&y%2;for(let s=0;s<width;s++){const x=reverse?width-1-s:s,idx=y*width+x,old=gray[idx],next=old<t?0:255,err=old-next;gray[idx]=next;(type==='riemersma'?kernels.floyd:kernels[type]).forEach(([dx,dy,w])=>{const nx=reverse?x-dx:x+dx,ny=y+dy;if(nx>=0&&nx<width&&ny>=0&&ny<height)gray[ny*width+nx]+=err*w;});}}for(let p=0,i=0;p<gray.length;p++,i+=4){const v=gray[p]<128?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function applyOrdered(imageData,matrix){const{data,width}=imageData,n=matrix.length,base=+controls.threshold.value,span=n===8?90:180;for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%width,y=Math.floor(p/width),t=base+(((matrix[y%n][x%n]+.5)/(n*n))-.5)*span,v=adjustedGray(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function hashNoise(x,y){let n=(x*374761393+y*668265263)^(x*y*1274126177);n=(n^(n>>>13))*1274126177;return((n^(n>>>16))>>>0)/4294967295;}
function applyBlueNoise(imageData){const{data,width}=imageData,base=+controls.threshold.value;for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%width,y=Math.floor(p/width),n=(hashNoise(x,y)+hashNoise(x+17,y+43)+hashNoise(x+59,y+11))/3,t=base+(n-.5)*115,v=adjustedGray(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function applyGrain(imageData){const{data,width}=imageData,base=+controls.threshold.value;for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%width,y=Math.floor(p/width),n=(hashNoise(x*3,y*3)*.65+hashNoise(x+91,y+17)*.35)-.5,v=adjustedGray(data[i],data[i+1],data[i+2])<base+n*82?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function grayMap(source){const a=new Float32Array(source.width*source.height),c=+controls.signalContrast.value,b=+controls.brightness.value;for(let p=0,i=0;p<a.length;p++,i+=4)a[p]=adjustedGray(source.data[i],source.data[i+1],source.data[i+2],c,b)/255;return a;}
function blurMap(src,w,h,r=3){let a=src,b=new Float32Array(src.length);for(let pass=0;pass<2;pass++){for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let k=-r;k<=r;k++){const xx=pass?x:clamp(x+k,0,w-1),yy=pass?clamp(y+k,0,h-1):y;s+=a[yy*w+xx];n++;}b[y*w+x]=s/n;}[a,b]=[b,a];}return a;}
function makeSurface(source){const g=grayMap(source),w=source.width,h=source.height,soft=blurMap(g,w,h,Math.max(2,Math.round(+controls.density.value)));const d=new Float32Array(g.length);for(let i=0;i<d.length;i++)d[i]=clamp((1-soft[i])*.78+(1-g[i])*.22,0,1);return{g,d,w,h};}
function sample(a,w,h,x,y){return a[clamp(Math.round(y),0,h-1)*w+clamp(Math.round(x),0,w-1)];}
function fieldCanvas(source){const out=document.createElement('canvas');out.width=source.width;out.height=source.height;const o=out.getContext('2d',{willReadFrequently:true});o.fillStyle='#fff';o.fillRect(0,0,out.width,out.height);o.strokeStyle='#000';o.fillStyle='#000';o.lineCap='round';o.lineJoin='round';return{out,o};}
function finish(out){const r=out.getContext('2d',{willReadFrequently:true}).getImageData(0,0,out.width,out.height);forceBW(r.data);return r;}
function envelope(t){const s=Math.sin(Math.PI*clamp(t,0,1));return s*s;}
function renderRibbon(source){const{s:d,w,h}=(()=>{const m=makeSurface(source);return{s:m.d,w:m.w,h:m.h};})(),{out,o}=fieldCanvas(source),amount=+controls.amount.value,warp=+controls.warp.value/100,flow=+controls.flow.value/100,spacing=Math.max(3,w/(amount*.72)),step=Math.max(1,h/360);o.lineWidth=Math.max(1,w/620);for(let x0=spacing/2;x0<w;x0+=spacing){o.beginPath();for(let y=0;y<=h;y+=step){const t=y/h,e=envelope(t),tone=sample(d,w,h,x0,y),gx=sample(d,w,h,x0+3,y)-sample(d,w,h,x0-3,y),bend=((tone-.5)*2*warp*w*.055+gx*flow*w*.12)*e;const x=x0+bend;if(y===0)o.moveTo(x,y);else o.lineTo(x,y);}o.stroke();}return finish(out);}
function renderContour(source){const{d,w,h}=makeSurface(source),{out,o}=fieldCanvas(source),amount=+controls.amount.value,warp=+controls.warp.value/100,flow=+controls.flow.value/100,spacing=Math.max(3,h/(amount*.72)),step=Math.max(1,w/420);o.lineWidth=Math.max(1,w/680);for(let y0=spacing/2;y0<h;y0+=spacing){o.beginPath();for(let x=0;x<=w;x+=step){const t=x/w,e=envelope(t),tone=sample(d,w,h,x,y0),gy=sample(d,w,h,x,y0+3)-sample(d,w,h,x,y0-3),y=y0+((tone-.5)*warp*h*.075+gy*flow*h*.14)*e;if(x===0)o.moveTo(x,y);else o.lineTo(x,y);}o.stroke();}return finish(out);}
function renderTopo(source){const{d,w,h}=makeSurface(source),{out,o}=fieldCanvas(source),levels=Math.max(8,Math.round(+controls.amount.value/4)),cell=Math.max(3,Math.round(+controls.density.value)),warp=+controls.warp.value/100;o.lineWidth=Math.max(1,w/760);const interp=(a,b,v)=>Math.abs(b-a)<1e-6?.5:(v-a)/(b-a);for(let li=1;li<levels;li++){const level=li/levels;for(let y=0;y<h-cell;y+=cell)for(let x=0;x<w-cell;x+=cell){const a=d[y*w+x],b=d[y*w+x+cell],c=d[(y+cell)*w+x+cell],e=d[(y+cell)*w+x],pts=[];if((a<level)!=(b<level))pts.push([x+cell*interp(a,b,level),y]);if((b<level)!=(c<level))pts.push([x+cell,y+cell*interp(b,c,level)]);if((e<level)!=(c<level))pts.push([x+cell*interp(e,c,level),y+cell]);if((a<level)!=(e<level))pts.push([x,y+cell*interp(a,e,level)]);if(pts.length>=2){o.beginPath();o.moveTo(pts[0][0],pts[0][1]);o.lineTo(pts[1][0],pts[1][1]);o.stroke();if(pts.length===4){o.beginPath();o.moveTo(pts[2][0],pts[2][1]);o.lineTo(pts[3][0],pts[3][1]);o.stroke();}}}}if(warp>.55){o.globalAlpha=.35;o.drawImage(out,1,0);o.globalAlpha=1;}return finish(out);}
function renderWave(source){const{d,w,h}=makeSurface(source),{out,o}=fieldCanvas(source),amount=+controls.amount.value,warp=+controls.warp.value/100,flow=+controls.flow.value/100,turb=+controls.turb.value/100,spacing=Math.max(3,w/(amount*.75)),step=Math.max(1,h/400);o.lineWidth=Math.max(1,w/720);for(let x0=spacing/2;x0<w;x0+=spacing){let phase=hashNoise(x0,17)*Math.PI*2;o.beginPath();for(let y=0;y<=h;y+=step){const t=y/h,e=envelope(t),tone=sample(d,w,h,x0,y),freq=.025+flow*.045,carrier=Math.sin(y*freq+phase),mod=Math.sin(y*.009+x0*.018)*turb,bend=(carrier*(3+tone*12)*warp+mod*10)*e;const x=x0+bend;if(y===0)o.moveTo(x,y);else o.lineTo(x,y);}o.stroke();}return finish(out);}
function renderRelief(source){const{g,d,w,h}=makeSurface(source),{out,o}=fieldCanvas(source),amount=+controls.amount.value,warp=+controls.warp.value/100,spacing=Math.max(3,w/(amount*.8)),step=Math.max(2,h/250),flow=+controls.flow.value/100;for(let x0=spacing/2;x0<w;x0+=spacing){for(let y=0;y<h;y+=step){const t=y/h,e=envelope(t),tone=1-sample(g,w,h,x0,y),depth=sample(d,w,h,x0,y),gx=sample(d,w,h,x0+2,y)-sample(d,w,h,x0-2,y),x=x0+(gx*w*.12*flow+(depth-.5)*w*.035*warp)*e;const len=step*(.35+tone*.9),thick=Math.max(.7,w/900+tone*w/520);o.lineWidth=thick;o.beginPath();o.moveTo(x,y);o.lineTo(x,y+len);o.stroke();}}return finish(out);}
function renderAscii(source){const{g,w,h}=makeSurface(source),{out,o}=fieldCanvas(source),density=+controls.density.value,amount=+controls.amount.value,cell=Math.max(6,Math.round(w/(amount*.42))),chars=' .:-=+*#%@';o.textAlign='center';o.textBaseline='middle';o.font=`${Math.max(7,Math.round(cell*1.15))}px ui-monospace,monospace`;for(let y=cell/2;y<h;y+=cell*1.25)for(let x=cell/2;x<w;x+=cell){const tone=sample(g,w,h,x,y),idx=clamp(Math.floor((1-tone)*(chars.length-1)*(.75+density*.025)),0,chars.length-1);o.fillText(chars[idx],x,y);}return finish(out);}
function isField(){return state.mode.startsWith('field')||state.mode==='ascii';}
function applyPreset(mode){const p=fieldPresets[mode];if(!p)return;Object.entries(p).forEach(([k,v])=>controls[k].value=v);updateLabels();}
function render(){if(!state.image)return;const{width,height}=getTargetSize(state.image);canvas.width=width;canvas.height=height;ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(state.image,0,0,width,height);let imageData=ctx.getImageData(0,0,width,height);switch(state.mode){case'floyd':case'atkinson':case'stucki':case'sierra':case'riemersma':applyDiffusion(imageData,state.mode);break;case'bayer':applyOrdered(imageData,bayer4);break;case'ordered8':applyOrdered(imageData,bayer8);break;case'bluenoise':applyBlueNoise(imageData);break;case'grain':applyGrain(imageData);break;case'fieldRibbon':imageData=renderRibbon(imageData);break;case'fieldContour':imageData=renderContour(imageData);break;case'fieldTopo':imageData=renderTopo(imageData);break;case'fieldWave':imageData=renderWave(imageData);break;case'fieldRelief':imageData=renderRelief(imageData);break;case'ascii':imageData=renderAscii(imageData);break;default:applyThreshold(imageData.data);}forceBW(imageData.data);if(state.inverted)invertPixels(imageData.data);ctx.putImageData(imageData,0,0);sizeBadge.textContent=`${width} × ${height}`;downloadBtn.disabled=false;}
function scheduleRender(){clearTimeout(state.renderTimer);state.renderTimer=setTimeout(render,55);}
function loadFile(file){if(!file||!file.type.startsWith('image/'))return;const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{if(state.image?.src?.startsWith('blob:'))URL.revokeObjectURL(state.image.src);state.image=image;emptyState.hidden=true;render();};image.onerror=()=>URL.revokeObjectURL(url);image.src=url;}
function reset(){state.image=null;state.mode='threshold';state.inverted=false;controls.threshold.value=128;controls.contrast.value=12;controls.resolution.value=576;ctx.clearRect(0,0,canvas.width,canvas.height);canvas.width=canvas.height=0;emptyState.hidden=false;downloadBtn.disabled=true;sizeBadge.textContent='— × —';document.querySelectorAll('.mode-chip').forEach((chip,index)=>chip.classList.toggle('active',index===0));syncControlGroups();updateLabels();}
function signed(v){const n=Number(v);return n>0?`+${n}`:String(n);}
function updateLabels(){outputs.threshold.textContent=controls.threshold.value;outputs.contrast.textContent=signed(controls.contrast.value);outputs.resolution.textContent=controls.resolution.value;['amount','density','flow','warp','turb','bias','brightness'].forEach(k=>outputs[k].textContent=controls[k].value);outputs.signalContrast.textContent=signed(controls.signalContrast.value);modeBadge.textContent=modeNames[state.mode];const chips=[...document.querySelectorAll('.mode-chip')];modeCount.textContent=`${chips.findIndex(chip=>chip.dataset.mode===state.mode)+1} / ${chips.length}`;}
function syncControlGroups(){basicControls.hidden=isField();signalControls.hidden=!isField();}
function applyLanguage(lang){state.language=lang;localStorage.setItem('dp-language',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=i18n[lang][el.dataset.i18n];if(value)el.textContent=value;});document.querySelector('meta[name="description"]').content=i18n[lang].description;}
function syncSettings(){const showPrinter=localStorage.getItem('dp-show-printer')!=='false',showTest=localStorage.getItem('dp-show-test')!=='false';document.querySelector('#showPrinterToggle').checked=showPrinter;document.querySelector('#showTestToggle').checked=showTest;document.querySelector('#printerPanel').hidden=!showPrinter;document.querySelector('#testPrinterBtn').hidden=!showTest;}
['cameraInput','libraryInput'].forEach(id=>document.querySelector(`#${id}`).addEventListener('change',e=>{loadFile(e.target.files?.[0]);e.target.value='';}));
document.querySelectorAll('.mode-chip').forEach(chip=>chip.addEventListener('click',()=>{state.mode=chip.dataset.mode;document.querySelectorAll('.mode-chip').forEach(item=>item.classList.toggle('active',item===chip));if(isField())applyPreset(state.mode);syncControlGroups();updateLabels();scheduleRender();}));
Object.values(controls).forEach(input=>input.addEventListener('input',()=>{updateLabels();scheduleRender();}));
document.querySelector('#invertBtn').addEventListener('click',()=>{state.inverted=!state.inverted;scheduleRender();});document.querySelector('#resetBtn').addEventListener('click',reset);
downloadBtn.addEventListener('click',e=>{e.preventDefault();if(!state.image)return;canvas.toBlob(blob=>{if(!blob)return;const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=`dither-printer-${state.mode}.png`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);},'image/png');});
const dialog=document.querySelector('#settingsDialog');document.querySelector('#settingsBtn').addEventListener('click',()=>dialog.showModal());document.querySelector('#closeSettingsBtn').addEventListener('click',()=>dialog.close());document.querySelector('#languageSelect').value=state.language;document.querySelector('#languageSelect').addEventListener('change',e=>applyLanguage(e.target.value));document.querySelector('#showPrinterToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-printer',e.target.checked);syncSettings();});document.querySelector('#showTestToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-test',e.target.checked);syncSettings();});
applyLanguage(state.language);syncSettings();updateLabels();syncControlGroups();
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const registrations=await navigator.serviceWorker.getRegistrations();await Promise.all(registrations.map(r=>r.unregister()));if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));}});