const $=s=>document.querySelector(s), canvas=$('#previewCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),emptyState=$('#emptyState'),downloadBtn=$('#downloadBtn'),modeBadge=$('#modeBadge'),sizeBadge=$('#sizeBadge'),modeCount=$('#modeCount'),basicControls=$('#basicControls'),signalControls=$('#signalControls'),asciiControls=$('#asciiControls');
const ids=['threshold','contrast','resolution','amount','density','flow','warp','turb','bias','signalContrast','brightness'];
const controls=Object.fromEntries(ids.map(id=>[id,$(`#${id}Range`)])),outputs=Object.fromEntries(ids.map(id=>[id,$(`#${id}Value`)]));
const state={image:null,mode:'threshold',inverted:false,renderTimer:null,language:localStorage.getItem('dp-language')||'fr'};
const modes=[...document.querySelectorAll('.mode-chip')];
const names=Object.fromEntries(modes.map(b=>[b.dataset.mode,b.textContent.toUpperCase()]));
const fieldPresets={fieldWarp:[96,3.2,72,58,54,0,38,-5],fieldElastic:[88,4.2,62,48,62,0,42,-8],fieldRefraction:[102,3.4,82,72,48,0,40,-6],fieldCompression:[118,2.8,76,38,66,0,44,-10],fieldThickness:[108,3.6,30,18,90,0,48,-12]};
const asciiPresets={asciiClassic:' .:-=+*#%@',asciiBlocks:' ░▒▓█',asciiTypewriter:' .,:;irsXA253hMHGS#9B&@',asciiMosaic:' ·○◌□◇△▽╱╲×●■◆',asciiNumbers:' 0123456789',asciiBinary:' 01',asciiHex:' 0123456789ABCDEF',asciiJapanese:'　・一アイウエオカキクケコサシスセソタチツテトナニヌネノマミムメモ',asciiEmoji:' ·○●◇◆☆★♧♣♡♥♢♦',textWords:null,textLetters:null,textSingle:null,textPair:null,textPattern:null};
const b4=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]],b8=[[0,48,12,60,3,51,15,63],[32,16,44,28,35,19,47,31],[8,56,4,52,11,59,7,55],[40,24,36,20,43,27,39,23],[2,50,14,62,1,49,13,61],[34,18,46,30,33,17,45,29],[10,58,6,54,9,57,5,53],[42,26,38,22,41,25,37,21]];
const kernels={floyd:[[1,0,7/16],[-1,1,3/16],[0,1,5/16],[1,1,1/16]],atkinson:[[1,0,1/8],[2,0,1/8],[-1,1,1/8],[0,1,1/8],[1,1,1/8],[0,2,1/8]],stucki:[[1,0,8/42],[2,0,4/42],[-2,1,2/42],[-1,1,4/42],[0,1,8/42],[1,1,4/42],[2,1,2/42],[-2,2,1/42],[-1,2,2/42],[0,2,4/42],[1,2,2/42],[2,2,1/42]],sierra:[[1,0,.5],[-1,1,.25],[0,1,.25]]};
const clamp=(v,a=0,b=255)=>Math.max(a,Math.min(b,v)),lum=(r,g,b)=>.2126*r+.7152*g+.0722*b;
function adjusted(r,g,b,c=+controls.contrast.value,br=0){const f=259*(c+255)/(255*(259-c));return clamp(f*(lum(r,g,b)-128)+128+br)}
function target(img){const w=+controls.resolution.value;return{width:w,height:Math.max(1,Math.round(w*img.naturalHeight/img.naturalWidth))}}
function bw(d){for(let i=0;i<d.length;i+=4){const v=d[i]<128?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}}
function invert(d){for(let i=0;i<d.length;i+=4)d[i]=d[i+1]=d[i+2]=d[i]===0?255:0}
function threshold(im){const t=+controls.threshold.value;for(let i=0;i<im.data.length;i+=4){const v=adjusted(im.data[i],im.data[i+1],im.data[i+2])<t?0:255;im.data[i]=im.data[i+1]=im.data[i+2]=v}}
function diffusion(im,type){const{data,width:w,height:h}=im,a=new Float32Array(w*h),t=+controls.threshold.value;for(let i=0,p=0;i<data.length;i+=4,p++)a[p]=adjusted(data[i],data[i+1],data[i+2]);for(let y=0;y<h;y++){const rev=type==='riemersma'&&y%2;for(let s=0;s<w;s++){const x=rev?w-1-s:s,i=y*w+x,n=a[i]<t?0:255,e=a[i]-n;a[i]=n;(type==='riemersma'?kernels.floyd:kernels[type]).forEach(([dx,dy,k])=>{const nx=rev?x-dx:x+dx,ny=y+dy;if(nx>=0&&nx<w&&ny<h)a[ny*w+nx]+=e*k})}}for(let p=0,i=0;p<a.length;p++,i+=4)data[i]=data[i+1]=data[i+2]=a[p]<128?0:255}
function ordered(im,m){const{data,width:w}=im,n=m.length,t0=+controls.threshold.value,span=n===8?90:180;for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%w,y=(p/w)|0,t=t0+(((m[y%n][x%n]+.5)/(n*n))-.5)*span,v=adjusted(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v}}
function noise(x,y){let n=(x*374761393+y*668265263)^(x*y*1274126177);n=(n^(n>>>13))*1274126177;return((n^(n>>>16))>>>0)/4294967295}
function noisy(im,grain=false){const{data,width:w}=im,t=+controls.threshold.value;for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%w,y=(p/w)|0,n=grain?noise(x*3,y*3)*.65+noise(x+91,y+17)*.35:(noise(x,y)+noise(x+17,y+43)+noise(x+59,y+11))/3,v=adjusted(data[i],data[i+1],data[i+2])<t+(n-.5)*(grain?82:115)?0:255;data[i]=data[i+1]=data[i+2]=v}}
function gray(im){const a=new Float32Array(im.width*im.height),c=+controls.signalContrast.value,b=+controls.brightness.value;for(let p=0,i=0;p<a.length;p++,i+=4)a[p]=adjusted(im.data[i],im.data[i+1],im.data[i+2],c,b)/255;return a}
function blur(a,w,h,r){let x=a,y=new Float32Array(a.length);for(let pass=0;pass<2;pass++){for(let j=0;j<h;j++)for(let i=0;i<w;i++){let s=0,n=0;for(let k=-r;k<=r;k++){const xx=pass?i:clamp(i+k,0,w-1),yy=pass?clamp(j+k,0,h-1):j;s+=x[yy*w+xx];n++}y[j*w+i]=s/n}[x,y]=[y,x]}return x}
const sample=(a,w,h,x,y)=>a[clamp(Math.round(y),0,h-1)*w+clamp(Math.round(x),0,w-1)];
function surface(im){const w=im.width,h=im.height,g=gray(im),soft=blur(g,w,h,Math.max(2,Math.round(+controls.density.value))),detail=new Float32Array(g.length);for(let i=0;i<g.length;i++)detail[i]=clamp((1-soft[i])*.72+(1-g[i])*.28,0,1);return{w,h,g,soft,detail}}
function outCanvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;const o=c.getContext('2d',{willReadFrequently:true});o.fillStyle='#fff';o.fillRect(0,0,w,h);o.strokeStyle=o.fillStyle='#000';o.lineCap=o.lineJoin='round';return{c,o}}
function finish(c){const im=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height);bw(im.data);return im}
function lineField(im,kind){const{w,h,g,soft,detail}=surface(im),{c,o}=outCanvas(w,h),amount=+controls.amount.value,flow=+controls.flow.value/100,warp=+controls.warp.value/100,thick=+controls.turb.value/100,bias=+controls.bias.value*Math.PI/180,spacing=Math.max(3,w/(amount*.78)),step=Math.max(1,h/420),env=y=>Math.pow(Math.sin(Math.PI*y/h),2);for(let x0=spacing/2;x0<w;x0+=spacing){let prev=null;o.beginPath();for(let y=0;y<=h;y+=step){const d=sample(detail,w,h,x0,y),tone=1-sample(g,w,h,x0,y),gx=sample(soft,w,h,x0+3,y)-sample(soft,w,h,x0-3,y),gy=sample(soft,w,h,x0,y+3)-sample(soft,w,h,x0,y-3),e=env(y);let dx=0;if(kind==='fieldWarp')dx=((d-.5)*w*.07+gx*w*.24)*warp*e;if(kind==='fieldElastic')dx=((d-.5)*w*.05+blur([gx],1,1,0)[0]*w*.2+Math.sin(y*.018+x0*.012)*w*.012)*warp*e;if(kind==='fieldRefraction')dx=(gx*w*.34+gy*w*.08+Math.sin((d+y/h)*12)*w*.012)*warp*e;if(kind==='fieldCompression')dx=((d-.5)*w*.045+gx*w*.12)*warp*e;if(kind==='fieldThickness')dx=gx*w*.06*warp*e;const x=x0+dx+Math.tan(bias)*(y-h/2)*.08;if(y===0)o.moveTo(x,y);else o.lineTo(x,y);const local=Math.max(.65,w/900+(tone*(.4+thick*2.5)+Math.abs(gx)*6)*w/780);if(prev!==null&&Math.abs(local-prev)>.35){o.stroke();o.beginPath();o.moveTo(x,y)}o.lineWidth=local;prev=local}o.stroke()}return finish(c)}
function braille(im){const{w,h,g}=surface(im),{c,o}=outCanvas(w,h),cell=Math.max(5,Math.round(w/(+controls.amount.value*.45))),dot=[[0,0,1],[0,1,2],[0,2,4],[1,0,8],[1,1,16],[1,2,32],[0,3,64],[1,3,128]];o.font=`${Math.round(cell*1.75)}px ui-monospace,monospace`;o.textAlign='center';o.textBaseline='middle';for(let y=0;y<h;y+=cell*2)for(let x=0;x<w;x+=cell){let code=0;dot.forEach(([dx,dy,b])=>{if(sample(g,w,h,x+dx*cell/2,y+dy*cell/2)<.52)code+=b});o.fillText(String.fromCharCode(0x2800+code),x+cell/2,y+cell)}return finish(c)}
function asciiPalette(mode){const t=($('#customText').value||'DITHER PRINTER').trim()||'DITHER PRINTER';if(mode==='textWords')return ' '+t+' ';if(mode==='textLetters')return ' '+[...new Set(t.replace(/\s/g,''))].join('');if(mode==='textSingle')return ' '+(t[0]||'A');if(mode==='textPair')return ' '+(t.slice(0,2)||'01');if(mode==='textPattern')return ' '+t;return asciiPresets[mode]||' .:-=+*#%@'}
function ascii(im,mode){if(mode==='asciiBraille')return braille(im);const{w,h,g}=surface(im),{c,o}=outCanvas(w,h),cell=Math.max(6,Math.round(w/(+controls.amount.value*.42))),palette=asciiPalette(mode),scale=.7+(+controls.density.value)*.035;o.textAlign='center';o.textBaseline='middle';o.font=`${Math.max(7,Math.round(cell*1.2))}px ui-monospace,SFMono-Regular,Menlo,monospace`;for(let y=cell/2;y<h;y+=cell*1.28)for(let x=cell/2;x<w;x+=cell){const tone=sample(g,w,h,x,y),idx=clamp(Math.floor((1-tone)*(palette.length-1)*scale),0,palette.length-1);o.fillText(palette[idx],x,y)}return finish(c)}
function isField(){return state.mode.startsWith('field')},isAscii(){return state.mode.startsWith('ascii')||state.mode.startsWith('text')}
function preset(mode){if(fieldPresets[mode])['amount','density','flow','warp','turb','bias','signalContrast','brightness'].forEach((k,i)=>controls[k].value=fieldPresets[mode][i]);else if(isAscii()){controls.amount.value=82;controls.density.value=4.2;controls.signalContrast.value=40;controls.brightness.value=0}labels()}
function render(){if(!state.image)return;const{width,height}=target(state.image);canvas.width=width;canvas.height=height;ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(state.image,0,0,width,height);let im=ctx.getImageData(0,0,width,height);switch(state.mode){case'floyd':case'atkinson':case'stucki':case'sierra':case'riemersma':diffusion(im,state.mode);break;case'bayer':ordered(im,b4);break;case'ordered8':ordered(im,b8);break;case'bluenoise':noisy(im);break;case'grain':noisy(im,true);break;default:if(isField())im=lineField(im,state.mode);else if(isAscii())im=ascii(im,state.mode);else threshold(im)}bw(im.data);if(state.inverted)invert(im.data);ctx.putImageData(im,0,0);sizeBadge.textContent=`${width} × ${height}`;downloadBtn.disabled=false}
function schedule(){clearTimeout(state.renderTimer);state.renderTimer=setTimeout(render,60)}
function load(file){if(!file||!file.type.startsWith('image/'))return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{state.image=img;emptyState.hidden=true;render()};img.src=url}
function labels(){outputs.threshold.textContent=controls.threshold.value;outputs.contrast.textContent=(+controls.contrast.value>0?'+':'')+controls.contrast.value;outputs.resolution.textContent=controls.resolution.value;['amount','density','flow','warp','turb','bias','brightness'].forEach(k=>outputs[k].textContent=controls[k].value);outputs.signalContrast.textContent=(+controls.signalContrast.value>0?'+':'')+controls.signalContrast.value;modeBadge.textContent=names[state.mode]||state.mode.toUpperCase();modeCount.textContent=`${modes.findIndex(b=>b.dataset.mode===state.mode)+1} / ${modes.length}`}
function groups(){basicControls.hidden=isField()||isAscii();signalControls.hidden=!(isField()||isAscii());asciiControls.hidden=!isAscii()}
['cameraInput','libraryInput'].forEach(id=>$(`#${id}`).addEventListener('change',e=>{load(e.target.files?.[0]);e.target.value=''}));
modes.forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;modes.forEach(x=>x.classList.toggle('active',x===b));preset(state.mode);groups();labels();schedule()}));
Object.values(controls).forEach(c=>c.addEventListener('input',()=>{labels();schedule()}));$('#customText').addEventListener('input',schedule);
$('#invertBtn').addEventListener('click',()=>{state.inverted=!state.inverted;schedule()});$('#resetBtn').addEventListener('click',()=>location.reload());
downloadBtn.addEventListener('click',()=>canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=`dither-printer-${state.mode}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)},'image/png'));
const dialog=$('#settingsDialog');$('#settingsBtn').addEventListener('click',()=>dialog.showModal());$('#closeSettingsBtn').addEventListener('click',()=>dialog.close());$('#languageSelect').value=state.language;function syncSettings(){const p=localStorage.getItem('dp-show-printer')!=='false',t=localStorage.getItem('dp-show-test')!=='false';$('#showPrinterToggle').checked=p;$('#showTestToggle').checked=t;$('#printerPanel').hidden=!p;$('#testPrinterBtn').hidden=!t}$('#showPrinterToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-printer',e.target.checked);syncSettings()});$('#showTestToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-test',e.target.checked);syncSettings()});$('#languageSelect').addEventListener('change',e=>{state.language=e.target.value;localStorage.setItem('dp-language',state.language)});
syncSettings();labels();groups();if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const rs=await navigator.serviceWorker.getRegistrations();await Promise.all(rs.map(r=>r.unregister()));if('caches'in window)await Promise.all((await caches.keys()).map(k=>caches.delete(k)))})