const canvas=document.querySelector('#previewCanvas');
const ctx=canvas.getContext('2d',{willReadFrequently:true});
const emptyState=document.querySelector('#emptyState');
const downloadBtn=document.querySelector('#downloadBtn');
const modeBadge=document.querySelector('#modeBadge');
const sizeBadge=document.querySelector('#sizeBadge');
const modeCount=document.querySelector('#modeCount');
const basicControls=document.querySelector('#basicControls');
const signalControls=document.querySelector('#signalControls');
const renderStatus=document.querySelector('#renderStatus');
const ids=['threshold','contrast','resolution','amount','density','flow','warp','turb','bias','signalContrast','brightness'];
const controls=Object.fromEntries(ids.map(id=>[id,document.querySelector(`#${id}Range`)]));
const outputs=Object.fromEntries(ids.map(id=>[id,document.querySelector(`#${id}Value`)]));
const state={image:null,mode:'threshold',inverted:false,renderTimer:null,renderToken:0,depthEstimator:null,language:localStorage.getItem('dp-language')||'fr'};
const modeNames={threshold:'SEUIL',floyd:'FLOYD–STEINBERG',atkinson:'ATKINSON',stucki:'STUCKI',sierra:'SIERRA LITE',bayer:'BAYER 4×4',ordered8:'ORDERED 8×8',bluenoise:'BLUE NOISE',riemersma:'RIEMERSMA',grain:'GRAIN',signalClassic:'SIGNAL CLASSIC',signalFlow:'SIGNAL FLOW',signal3dFast:'SIGNAL 3D FAST',signal3dAi:'SIGNAL 3D IA'};
const signalPresets={signalClassic:{amount:84,density:4.2,flow:42,warp:20,turb:8,bias:0,signalContrast:30,brightness:0},signalFlow:{amount:118,density:3.4,flow:84,warp:38,turb:22,bias:-8,signalContrast:34,brightness:-4},signal3dFast:{amount:126,density:3.1,flow:72,warp:58,turb:12,bias:0,signalContrast:42,brightness:-8},signal3dAi:{amount:138,density:2.8,flow:82,warp:68,turb:10,bias:0,signalContrast:46,brightness:-10}};
const i18n={fr:{tagline:'LABORATOIRE D’IMAGE THERMIQUE',camera:'Prise de vue',cameraHelp:'Ouvrir l’appareil photo',library:'Bibliothèque',libraryHelp:'Choisir une photo',addImage:'Ajoute une image',emptyHelp:'Elle sera convertie en noir et blanc pur.',renderStyle:'Rendu',threshold:'Seuil',grain:'Grain',contrast:'Contraste',resolution:'Résolution',brightness:'Luminosité',ipAddress:'Adresse IP',printerHelp:'L’iPhone et l’imprimante doivent être sur le même réseau.',printImage:'Imprimer l’image',invert:'Inverser',exportPng:'Exporter PNG',footer:'100 % noir · 100 % blanc · aucun gris',settings:'Paramètres',language:'Langue',showPrinting:'Afficher toute la partie impression',showTest:'Afficher le bouton de test',description:'Transformez vos photos en noir et blanc pur, avec des algorithmes de tramage et des rendus Signal optimisés pour l’impression thermique ou l’export PNG.',aiLoading:'Chargement du modèle 3D IA…',aiProcessing:'Estimation des volumes…',aiFallback:'IA indisponible : rendu 3D Fast utilisé.'},en:{tagline:'THERMAL IMAGE LAB',camera:'Camera',cameraHelp:'Open the camera',library:'Library',libraryHelp:'Choose a photo',addImage:'Add an image',emptyHelp:'It will be converted to pure black and white.',renderStyle:'Rendering',threshold:'Threshold',grain:'Grain',contrast:'Contrast',resolution:'Resolution',brightness:'Brightness',ipAddress:'IP address',printerHelp:'The iPhone and printer must be on the same network.',printImage:'Print image',invert:'Invert',exportPng:'Export PNG',footer:'100% black · 100% white · no gray',settings:'Settings',language:'Language',showPrinting:'Show the entire printing section',showTest:'Show the printer test button',description:'Convert photos to pure black and white using dithering algorithms and Signal renderers optimized for thermal printing or PNG export.',aiLoading:'Loading the 3D AI model…',aiProcessing:'Estimating depth…',aiFallback:'AI unavailable: using 3D Fast.'},es:{tagline:'LABORATORIO DE IMAGEN TÉRMICA',camera:'Cámara',cameraHelp:'Abrir la cámara',library:'Biblioteca',libraryHelp:'Elegir una foto',addImage:'Añade una imagen',emptyHelp:'Se convertirá a blanco y negro puro.',renderStyle:'Renderizado',threshold:'Umbral',grain:'Grano',contrast:'Contraste',resolution:'Resolución',brightness:'Brillo',ipAddress:'Dirección IP',printerHelp:'El iPhone y la impresora deben estar en la misma red.',printImage:'Imprimir imagen',invert:'Invertir',exportPng:'Exportar PNG',footer:'100 % negro · 100 % blanco · sin gris',settings:'Ajustes',language:'Idioma',showPrinting:'Mostrar toda la sección de impresión',showTest:'Mostrar el botón de prueba',description:'Convierte fotos a blanco y negro puro con algoritmos de tramado y renderizados Signal optimizados para impresión térmica o exportación PNG.',aiLoading:'Cargando el modelo 3D IA…',aiProcessing:'Estimando los volúmenes…',aiFallback:'IA no disponible: se usa 3D Fast.'}};
const bayer4=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]];
const bayer8=[[0,48,12,60,3,51,15,63],[32,16,44,28,35,19,47,31],[8,56,4,52,11,59,7,55],[40,24,36,20,43,27,39,23],[2,50,14,62,1,49,13,61],[34,18,46,30,33,17,45,29],[10,58,6,54,9,57,5,53],[42,26,38,22,41,25,37,21]];
const kernels={floyd:[[1,0,7/16],[-1,1,3/16],[0,1,5/16],[1,1,1/16]],atkinson:[[1,0,1/8],[2,0,1/8],[-1,1,1/8],[0,1,1/8],[1,1,1/8],[0,2,1/8]],stucki:[[1,0,8/42],[2,0,4/42],[-2,1,2/42],[-1,1,4/42],[0,1,8/42],[1,1,4/42],[2,1,2/42],[-2,2,1/42],[-1,2,2/42],[0,2,4/42],[1,2,2/42],[2,2,1/42]],sierra:[[1,0,.5],[-1,1,.25],[0,1,.25]]};
function clamp(v,min=0,max=255){return Math.max(min,Math.min(max,v));}
function luminance(r,g,b){return .2126*r+.7152*g+.0722*b;}
function adjustedGray(r,g,b,contrast=Number(controls.contrast.value),brightness=0){const f=(259*(contrast+255))/(255*(259-contrast));return clamp(f*(luminance(r,g,b)-128)+128+brightness);}
function getTargetSize(image){const width=Number(controls.resolution.value);return{width,height:Math.max(1,Math.round(width*image.naturalHeight/image.naturalWidth))};}
function forceBW(data){for(let i=0;i<data.length;i+=4){const v=data[i]<128?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function applyThreshold(data){const t=Number(controls.threshold.value);for(let i=0;i<data.length;i+=4){const v=adjustedGray(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function applyDiffusion(imageData,type){const{data,width,height}=imageData,gray=new Float32Array(width*height),t=Number(controls.threshold.value);for(let i=0,p=0;i<data.length;i+=4,p++)gray[p]=adjustedGray(data[i],data[i+1],data[i+2]);for(let y=0;y<height;y++){const reverse=type==='riemersma'&&y%2;for(let s=0;s<width;s++){const x=reverse?width-1-s:s,idx=y*width+x,old=gray[idx],next=old<t?0:255,err=old-next;gray[idx]=next;(type==='riemersma'?kernels.floyd:kernels[type]).forEach(([dx,dy,w])=>{const nx=reverse?x-dx:x+dx,ny=y+dy;if(nx>=0&&nx<width&&ny>=0&&ny<height)gray[ny*width+nx]+=err*w;});}}for(let p=0,i=0;p<gray.length;p++,i+=4){const v=gray[p]<128?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function applyOrdered(imageData,matrix){const{data,width}=imageData,n=matrix.length,base=Number(controls.threshold.value),span=n===8?90:180;for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%width,y=Math.floor(p/width),t=base+(((matrix[y%n][x%n]+.5)/(n*n))-.5)*span,v=adjustedGray(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function hashNoise(x,y){let n=(x*374761393+y*668265263)^(x*y*1274126177);n=(n^(n>>>13))*1274126177;return((n^(n>>>16))>>>0)/4294967295;}
function applyBlueNoise(imageData){const{data,width}=imageData,base=Number(controls.threshold.value);for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%width,y=Math.floor(p/width),n=(hashNoise(x,y)+hashNoise(x+17,y+43)+hashNoise(x+59,y+11))/3,t=base+(n-.5)*115,v=adjustedGray(data[i],data[i+1],data[i+2])<t?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function applyGrain(imageData){const{data,width}=imageData,base=Number(controls.threshold.value);for(let i=0,p=0;i<data.length;i+=4,p++){const x=p%width,y=Math.floor(p/width),n=(hashNoise(x*3,y*3)*.65+hashNoise(x+91,y+17)*.35)-.5,v=adjustedGray(data[i],data[i+1],data[i+2])<base+n*82?0:255;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}
function grayMap(source){const a=new Float32Array(source.width*source.height),c=Number(controls.signalContrast.value),b=Number(controls.brightness.value);for(let p=0,i=0;p<a.length;p++,i+=4)a[p]=adjustedGray(source.data[i],source.data[i+1],source.data[i+2],c,b)/255;return a;}
function blurMap(src,w,h,r=3){let a=src,b=new Float32Array(src.length);for(let pass=0;pass<2;pass++){for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let k=-r;k<=r;k++){const xx=pass?x:Math.max(0,Math.min(w-1,x+k)),yy=pass?Math.max(0,Math.min(h-1,y+k)):y;s+=a[yy*w+xx];n++;}b[y*w+x]=s/n;}[a,b]=[b,a];}return a;}
function fastDepth(source){const{width:w,height:h}=source,g=grayMap(source),b1=blurMap(g,w,h,3),b2=blurMap(g,w,h,12),d=new Float32Array(g.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,gx=b1[y*w+Math.min(w-1,x+2)]-b1[y*w+Math.max(0,x-2)],gy=b1[Math.min(h-1,y+2)*w+x]-b1[Math.max(0,y-2)*w+x],center=1-Math.hypot(x-w/2,y-h/2)/Math.hypot(w/2,h/2);d[i]=clamp((1-b2[i])*.5+center*.18+Math.hypot(gx,gy)*.8,0,1);}return d;}
async function aiDepth(source){if(!state.depthEstimator){renderStatus.hidden=false;renderStatus.textContent=i18n[state.language].aiLoading;const mod=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm');state.depthEstimator=await mod.pipeline('depth-estimation','Xenova/depth-anything-small-hf',{dtype:'q8'});}renderStatus.textContent=i18n[state.language].aiProcessing;const temp=document.createElement('canvas');temp.width=source.width;temp.height=source.height;temp.getContext('2d').putImageData(source,0,0);const result=await state.depthEstimator(temp.toDataURL('image/jpeg',.86));const raw=result.depth||result.predicted_depth||result;const rw=raw.width||source.width,rh=raw.height||source.height,data=raw.data||raw;const out=new Float32Array(source.width*source.height);let min=Infinity,max=-Infinity;for(const v of data){if(v<min)min=v;if(v>max)max=v;}for(let y=0;y<source.height;y++)for(let x=0;x<source.width;x++){const sx=Math.min(rw-1,Math.floor(x*rw/source.width)),sy=Math.min(rh-1,Math.floor(y*rh/source.height)),v=data[sy*rw+sx];out[y*source.width+x]=(v-min)/(max-min||1);}return out;}
function applySignal(source,kind,depth=null){const{width:w,height:h}=source,g=grayMap(source),out=document.createElement('canvas');out.width=w;out.height=h;const o=out.getContext('2d',{willReadFrequently:true});o.fillStyle='#fff';o.fillRect(0,0,w,h);o.strokeStyle='#000';o.lineCap='round';const amount=+controls.amount.value,density=+controls.density.value,flow=+controls.flow.value/100,warp=+controls.warp.value/100,turb=+controls.turb.value/100,bias=+controls.bias.value*Math.PI/180;const spacing=Math.max(2,h/amount*density/3.6),step=Math.max(.8,w/520),sample=(a,x,y)=>a[Math.max(0,Math.min(h-1,Math.round(y)))*w+Math.max(0,Math.min(w-1,Math.round(x)))];o.lineWidth=Math.max(.8,w/(680-density*22));for(let sy=-spacing;sy<h+spacing;sy+=spacing){for(let sx=-spacing;sx<w+spacing;sx+=spacing*1.4){let x=sx+(hashNoise(sx,sy)-.5)*spacing,y=sy;o.beginPath();let live=false;for(let n=0;n<Math.max(w,h)*1.4;n+=step){if(x<1||x>=w-1||y<1||y>=h-1)break;const map=depth||g,gx=sample(map,x+2,y)-sample(map,x-2,y),gy=sample(map,x,y+2)-sample(map,x,y-2),edge=Math.hypot(gx,gy),tone=1-sample(g,x,y);let angle=Math.atan2(gy,gx)+Math.PI/2+bias;if(kind==='classic')angle=.2*(1-flow)+angle*flow;if(kind==='flow')angle+=Math.sin(x*.018+y*.011)*warp*1.4;if(kind.startsWith('3d')){const nx=-gx,ny=-gy,nz=.45,light=(nx*-.55+ny*-.65+nz*.5)/(Math.hypot(nx,ny,nz)||1);angle+=light*warp*1.3+Math.sin((x+y)*.018)*warp*.35;}angle+=(hashNoise(Math.floor(x/8),Math.floor(y/8))-.5)*Math.PI*turb;x+=Math.cos(angle)*step*(1.2+flow);y+=Math.sin(angle)*step*(1.2+flow);if(tone>.08||edge>.025){if(!live){o.moveTo(x,y);live=true;}else o.lineTo(x,y);}if(tone<.05&&edge<.01&&n>20)break;}if(live)o.stroke();}}const result=o.getImageData(0,0,w,h);forceBW(result.data);return result;}
function invertPixels(data){for(let i=0;i<data.length;i+=4)data[i]=data[i+1]=data[i+2]=data[i]===0?255:0;}
function isSignal(){return state.mode.startsWith('signal');}
function applyPreset(mode){const preset=signalPresets[mode];if(!preset)return;Object.entries(preset).forEach(([key,value])=>controls[key].value=value);updateLabels();}
async function render(){if(!state.image)return;const token=++state.renderToken,{width,height}=getTargetSize(state.image);canvas.width=width;canvas.height=height;ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(state.image,0,0,width,height);let imageData=ctx.getImageData(0,0,width,height);try{switch(state.mode){case'floyd':case'atkinson':case'stucki':case'sierra':case'riemersma':applyDiffusion(imageData,state.mode);break;case'bayer':applyOrdered(imageData,bayer4);break;case'ordered8':applyOrdered(imageData,bayer8);break;case'bluenoise':applyBlueNoise(imageData);break;case'grain':applyGrain(imageData);break;case'signalClassic':imageData=applySignal(imageData,'classic');break;case'signalFlow':imageData=applySignal(imageData,'flow');break;case'signal3dFast':imageData=applySignal(imageData,'3d-fast',fastDepth(imageData));break;case'signal3dAi':try{imageData=applySignal(imageData,'3d-ai',await aiDepth(imageData));}catch(error){console.error(error);renderStatus.hidden=false;renderStatus.textContent=i18n[state.language].aiFallback;imageData=applySignal(imageData,'3d-fast',fastDepth(imageData));setTimeout(()=>renderStatus.hidden=true,2600);}break;default:applyThreshold(imageData.data);}}finally{if(state.mode!=='signal3dAi'||renderStatus.textContent===i18n[state.language].aiProcessing)renderStatus.hidden=true;}if(token!==state.renderToken)return;forceBW(imageData.data);if(state.inverted)invertPixels(imageData.data);ctx.putImageData(imageData,0,0);sizeBadge.textContent=`${width} × ${height}`;downloadBtn.disabled=false;}
function scheduleRender(){clearTimeout(state.renderTimer);state.renderTimer=setTimeout(render,70);}
function loadFile(file){if(!file||!file.type.startsWith('image/'))return;const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{if(state.image?.src?.startsWith('blob:'))URL.revokeObjectURL(state.image.src);state.image=image;emptyState.hidden=true;render();};image.onerror=()=>URL.revokeObjectURL(url);image.src=url;}
function reset(){state.image=null;state.mode='threshold';state.inverted=false;controls.threshold.value=128;controls.contrast.value=12;controls.resolution.value=576;ctx.clearRect(0,0,canvas.width,canvas.height);canvas.width=canvas.height=0;emptyState.hidden=false;downloadBtn.disabled=true;sizeBadge.textContent='— × —';document.querySelectorAll('.mode-chip').forEach((chip,index)=>chip.classList.toggle('active',index===0));syncControlGroups();updateLabels();}
function signed(v){const n=Number(v);return n>0?`+${n}`:String(n);}
function updateLabels(){outputs.threshold.textContent=controls.threshold.value;outputs.contrast.textContent=signed(controls.contrast.value);outputs.resolution.textContent=controls.resolution.value;['amount','density','flow','warp','turb','bias','brightness'].forEach(k=>outputs[k].textContent=controls[k].value);outputs.signalContrast.textContent=signed(controls.signalContrast.value);modeBadge.textContent=modeNames[state.mode];const chips=[...document.querySelectorAll('.mode-chip')];modeCount.textContent=`${chips.findIndex(chip=>chip.dataset.mode===state.mode)+1} / ${chips.length}`;}
function syncControlGroups(){basicControls.hidden=isSignal();signalControls.hidden=!isSignal();}
function applyLanguage(lang){state.language=lang;localStorage.setItem('dp-language',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=i18n[lang][el.dataset.i18n];if(value)el.textContent=value;});document.querySelector('meta[name="description"]').content=i18n[lang].description;}
function syncSettings(){const showPrinter=localStorage.getItem('dp-show-printer')!=='false',showTest=localStorage.getItem('dp-show-test')!=='false';document.querySelector('#showPrinterToggle').checked=showPrinter;document.querySelector('#showTestToggle').checked=showTest;document.querySelector('#printerPanel').hidden=!showPrinter;document.querySelector('#testPrinterBtn').hidden=!showTest;}
['cameraInput','libraryInput'].forEach(id=>document.querySelector(`#${id}`).addEventListener('change',e=>{loadFile(e.target.files?.[0]);e.target.value='';}));
document.querySelectorAll('.mode-chip').forEach(chip=>chip.addEventListener('click',()=>{state.mode=chip.dataset.mode;document.querySelectorAll('.mode-chip').forEach(item=>item.classList.toggle('active',item===chip));if(isSignal())applyPreset(state.mode);syncControlGroups();updateLabels();scheduleRender();}));
Object.values(controls).forEach(input=>input.addEventListener('input',()=>{updateLabels();scheduleRender();}));
document.querySelector('#invertBtn').addEventListener('click',()=>{state.inverted=!state.inverted;scheduleRender();});document.querySelector('#resetBtn').addEventListener('click',reset);
downloadBtn.addEventListener('click',e=>{e.preventDefault();if(!state.image)return;canvas.toBlob(blob=>{if(!blob)return;const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=`dither-printer-${state.mode}.png`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);},'image/png');});
const dialog=document.querySelector('#settingsDialog');document.querySelector('#settingsBtn').addEventListener('click',()=>dialog.showModal());document.querySelector('#closeSettingsBtn').addEventListener('click',()=>dialog.close());document.querySelector('#languageSelect').value=state.language;document.querySelector('#languageSelect').addEventListener('change',e=>applyLanguage(e.target.value));document.querySelector('#showPrinterToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-printer',e.target.checked);syncSettings();});document.querySelector('#showTestToggle').addEventListener('change',e=>{localStorage.setItem('dp-show-test',e.target.checked);syncSettings();});
applyLanguage(state.language);syncSettings();updateLabels();syncControlGroups();
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const registrations=await navigator.serviceWorker.getRegistrations();await Promise.all(registrations.map(r=>r.unregister()));if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));}});